### ISSUE TITLE
Viết testcases cho các chức năng.

### ISSUE THREAD

**Issue by nguyenmaianh249** [trandinh123/cnpm-team-2#20]

**Comment by nguyenmaianh249** [comment]
- [x] Viết các testcases cho các chức năng nhắn tin, kết bạn, tìm kiếm, gọi điện.
- [x] Trong từng testcases, viết các test steps và expected results của từng step.

**Comment by DucAnh2611** [comment]
Tốt, chia thành từng mục, rõ ràng
